version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: echolist-postgres
    environment:
      POSTGRES_USER: echolist
      POSTGRES_PASSWORD: echolist_password
      POSTGRES_DB: echolist
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - echolist-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U echolist"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  echolist-network:
    driver: bridge

volumes:
  postgres_data:
