"""Initial migration

Revision ID: a0431d8d375c
Revises: 
Create Date: 2025-07-22 00:05:33.659864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0431d8d375c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('voice_speed_setting', sa.Integer(), nullable=False),
    sa.Column('contrast_setting', sa.String(), nullable=False),
    sa.Column('confirmation_nudges_setting', sa.Boolean(), nullable=False),
    sa.Column('daily_streak_count', sa.Integer(), nullable=False),
    sa.Column('last_summary_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('connections',
    sa.Column('connection_id', sa.Integer(), nullable=False),
    sa.Column('user_a_id', sa.Integer(), nullable=False),
    sa.Column('user_b_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.Enum('FAMILY', 'FRIEND', 'COLLEAGUE', name='connectiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', name='connectionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_a_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('connection_id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='unique_connection')
    )
    op.create_index(op.f('ix_connections_connection_id'), 'connections', ['connection_id'], unique=False)
    op.create_table('sections',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('display_color', sa.String(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('template_description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_sections_section_id'), 'sections', ['section_id'], unique=False)
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_task', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('vector_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('original_audio_url', sa.String(), nullable=True),
    sa.Column('last_modified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['last_modified_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=False)
    op.create_table('section_access',
    sa.Column('section_access_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('allowed_connection_type', sa.Enum('FAMILY', 'FRIEND', 'COLLEAGUE', name='connectiontype'), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['sections.section_id'], ),
    sa.PrimaryKeyConstraint('section_access_id'),
    sa.UniqueConstraint('section_id', 'allowed_connection_type', name='unique_section_access')
    )
    op.create_index(op.f('ix_section_access_section_access_id'), 'section_access', ['section_access_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_section_access_section_access_id'), table_name='section_access')
    op.drop_table('section_access')
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_sections_section_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_connections_connection_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
